services:
  - type: web
    name: community-drainage-monitoring-system
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir backend app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
